"""
visualizer.py — Plotly-based interactive visualization for anomaly detection.

Creates high-impact, interactive charts highlighting detected market manipulation
phases, price kinematics, and volume spikes. Ready for Jupyter Notebooks or
web dashboards.
"""

from __future__ import annotations

from typing import List, Optional
import pandas as pd

try:
    import plotly.graph_objects as go
    from plotly.subplots import make_subplots
    HAS_PLOTLY = True
except ImportError:
    HAS_PLOTLY = False

from shield_regime.models.alert import Alert
from shield_regime.indicators.velocity import velocity_zscore


def plot_alerts(
    df: pd.DataFrame,
    alerts: List[Alert],
    ticker: str = "UNKNOWN",
    lookback: int = 40,
) -> Optional[go.Figure]:
    """Generate an interactive Plotly figure visualizing detected anomalies.

    Subplot 1: Price series with shaded anomaly windows and peak flags.
    Subplot 2: Velocity Z-score with trigger thresholds.

    Parameters
    ----------
    df : pd.DataFrame
        Must contain 'close' and 'volume'. Index should be DatetimeIndex.
    alerts : List[Alert]
        List of Alert objects generated by the detector.
    ticker : str, default "UNKNOWN"
        Ticker symbol.
    lookback : int, default 40
        Lookback window used for indicators.

    Returns
    -------
    plotly.graph_objects.Figure or None
        Returns None if plotly is not installed, otherwise returns the Figure.
    """
    if not HAS_PLOTLY:
        print("[WARN] Plotly is not installed. Visualizer disabled.")
        return None

    # Calculate indicators for visualization
    vel_z = velocity_zscore(df["close"], lookback=lookback, use_pct=True)

    # Create Subplots
    fig = make_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        vertical_spacing=0.08,
        row_heights=[0.65, 0.35],
        subplot_titles=(f"{ticker} Close Price with Detected Anomaly Windows", "Price Velocity Z-Score"),
    )

    # 1. Plot Close Price
    fig.add_trace(
        go.Scatter(
            x=df.index,
            y=df["close"],
            mode="lines",
            name="Close Price",
            line=dict(color="#1f77b4", width=2),
        ),
        row=1,
        col=1,
    )

    # Highlight Alerts
    for idx, alert in enumerate(alerts, 1):
        # Shaded background region for the whole alert duration
        fig.add_vrect(
            x0=alert.start_date,
            x1=alert.end_date,
            fillcolor="rgba(239, 83, 80, 0.2)",
            layer="below",
            line_width=0,
            annotation_text=f"Anomaly #{idx}",
            annotation_position="top left",
            row=1,
            col=1,
        )

        # Draw a marker at the start of the pump
        fig.add_trace(
            go.Scatter(
                x=[alert.start_date],
                y=[df.loc[alert.start_date, "close"]],
                mode="markers+text",
                name=f"Pump Start #{idx}",
                marker=dict(symbol="triangle-up", size=12, color="#4CAF50"),
                text=[f"Pump Start"],
                textposition="bottom center",
                showlegend=False,
            ),
            row=1,
            col=1,
        )

        # Draw a marker at the end/low of the dump
        fig.add_trace(
            go.Scatter(
                x=[alert.end_date],
                y=[df.loc[alert.end_date, "close"]],
                mode="markers+text",
                name=f"Dump Low #{idx}",
                marker=dict(symbol="triangle-down", size=12, color="#F44336"),
                text=[f"Dump Low ({alert.metrics.get('dump_drop_pct', 0.0):.1f}%)"],
                textposition="top center",
                showlegend=False,
            ),
            row=1,
            col=1,
        )

    # 2. Plot Velocity Z-Score
    fig.add_trace(
        go.Scatter(
            x=vel_z.index,
            y=vel_z,
            mode="lines",
            name="Velocity Z-Score",
            line=dict(color="#e377c2", width=1.5),
        ),
        row=2,
        col=1,
    )

    # Threshold guidelines
    fig.add_hline(y=2.5, line_dash="dash", line_color="#EF5350", annotation_text="+2.5σ Limit", row=2, col=1)
    fig.add_hline(y=-2.5, line_dash="dash", line_color="#EF5350", annotation_text="-2.5σ Limit", row=2, col=1)
    fig.add_hline(y=0.0, line_dash="dot", line_color="#7f7f7f", row=2, col=1)

    # Styling and Layout
    fig.update_layout(
        title=dict(
            text=f"<b>🛡️ ShieldRegime Analysis — {ticker}</b>",
            x=0.5,
            xanchor="center",
            font=dict(size=18, family="Arial"),
        ),
        template="plotly_white",
        showlegend=True,
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        margin=dict(l=50, r=50, t=100, b=50),
        hovermode="x unified",
    )

    fig.update_yaxes(title_text="Price", row=1, col=1)
    fig.update_yaxes(title_text="Z-Score", row=2, col=1)
    fig.update_xaxes(title_text="Date", row=2, col=1)

    return fig
